config/routes.rb
Prototipo::Application.routes.draw do
  resources :gift_categories

  resources :product_categories

  resources :categories

  resources :gifts

  resources :form_of_payments

  resources :users

  resources :purchases

  get "pages/home"

  get "pages/contact"

  get "pages/how_it_works"

  get "pages/who_we_are"

  resources :offers

  resources :companies

  resources :products

end

app/models/form_of_payment.rb
class FormOfPayment < ActiveRecord::Base
end

app/controllers/form_of_payments_controller.rb
class FormOfPaymentsController < ApplicationController
  # GET /form_of_payments
  # GET /form_of_payments.json
  def index
    @form_of_payments = FormOfPayment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @form_of_payments }
    end
  end

  # GET /form_of_payments/1
  # GET /form_of_payments/1.json
  def show
    @form_of_payment = FormOfPayment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @form_of_payment }
    end
  end

  # GET /form_of_payments/new
  # GET /form_of_payments/new.json
  def new
    @form_of_payment = FormOfPayment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @form_of_payment }
    end
  end

  # GET /form_of_payments/1/edit
  def edit
    @form_of_payment = FormOfPayment.find(params[:id])
  end

  # POST /form_of_payments
  # POST /form_of_payments.json
  def create
    @form_of_payment = FormOfPayment.new(params[:form_of_payment])

    respond_to do |format|
      if @form_of_payment.save
        format.html { redirect_to @form_of_payment, :notice => 'Form of payment was successfully created.' }
        format.json { render :json => @form_of_payment, :status => :created, :location => @form_of_payment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @form_of_payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /form_of_payments/1
  # PUT /form_of_payments/1.json
  def update
    @form_of_payment = FormOfPayment.find(params[:id])

    respond_to do |format|
      if @form_of_payment.update_attributes(params[:form_of_payment])
        format.html { redirect_to @form_of_payment, :notice => 'Form of payment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @form_of_payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /form_of_payments/1
  # DELETE /form_of_payments/1.json
  def destroy
    @form_of_payment = FormOfPayment.find(params[:id])
    @form_of_payment.destroy

    respond_to do |format|
      format.html { redirect_to form_of_payments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/form_of_payments_helper.rb
module FormOfPaymentsHelper
end

app/views/form_of_payments/_form.html.erb
<%= form_for(@form_of_payment) do |f| %>
  <% if @form_of_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form_of_payment.errors.count, "error") %> prohibited this form_of_payment from being saved:</h2>

      <ul>
      <% @form_of_payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/form_of_payments/edit.html.erb
<h1>Editing form_of_payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @form_of_payment %> |
<%= link_to 'Back', form_of_payments_path %>

app/views/form_of_payments/index.html.erb
<h1>Listing form_of_payments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @form_of_payments.each do |form_of_payment| %>
  <tr>
    <td><%= form_of_payment.name %></td>
    <td><%= form_of_payment.image_url %></td>
    <td><%= link_to 'Show', form_of_payment %></td>
    <td><%= link_to 'Edit', edit_form_of_payment_path(form_of_payment) %></td>
    <td><%= link_to 'Destroy', form_of_payment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Form of payment', new_form_of_payment_path %>

app/views/form_of_payments/new.html.erb
<h1>New form_of_payment</h1>

<%= render 'form' %>

<%= link_to 'Back', form_of_payments_path %>

app/views/form_of_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @form_of_payment.name %>
</p>

<p>
  <b>Image url:</b>
  <%= @form_of_payment.image_url %>
</p>


<%= link_to 'Edit', edit_form_of_payment_path(@form_of_payment) %> |
<%= link_to 'Back', form_of_payments_path %>